### ISSUE TITLE
Cannot save model

### ISSUE THREAD

**Issue by rudxokim** [irllabs/ml-lib#166]
Thanks for your effort.

I tried to save my trained daw model with my own name and console says

error: ml.dtw: unable to write trains data to path: [my own name].data

I tried with /foldername/name, or just name.. but same result

I'm running ml. libraries on max 8 with MacOS mojave.

**Comment by rudxokim** [comment]
![image](https://user-images.githubusercontent.com/29219491/61456677-9ff56880-a9a1-11e9-9c1b-e4846aca1b2c.png)

Here's my patch

**Comment by NiccoloGranieri** [comment]
Hi @rudxokim, thanks for you interest in ml.lib. I currently can't reproduce your issue. I tried to save the data and model using your same naming convention, and I didn't encounter any errors.
Running:
`(write /motion_data/_18_9_18_32)`
saves correctly both the data and the model in the folder called motion_data in my root folder. This provided that a motion_data folder already exists in my root.

I was able to see the same error only if the folder was not present, making it impossible for ml.lib to save to the specified location.

Could you please double check for me that the path you are trying to save the file to is valid, and there is a folder called motion_data in your root?

**Comment by rudxokim** [comment]
Thanks for your prompt response.

I tried without the folder name like just [write motion], but result was same.

Even the provided help file shows same error. getting weird.

root folder means current patch file location right?

I tried sfplay~ to test out my 'root folder' with messages [open demo.wav] and worked without any problem.

Regards, Kim

**Comment by NiccoloGranieri** [comment]
No problem @rudxokim,

It should not work without the folder name, so that's behaving as expected.

The provided help file shows the same error because there is no such path as /path/to/my_ml-lib_data on your laptop, so ml.lib is unable to find the correct path where to save the data and model.

The root folder is not the current patch file location, the root folder or root directory is the "highest" directory in the hierarchy. So to be able to save the data in the same folder you need to find the full path to the folder in which your Max Patch is saved. Because you're on Mojave, the easieast way to do so is to:

- Right click on the folder in which your Max patch is saved
- Press the [option ⌥] key (or [alt ⌥] key) to show further options
- Click on "Copy "_name_of_folder_" as Pathname

![Screenshot 2019-07-18 at 14 07 05](https://user-images.githubusercontent.com/14252117/61459952-b7aefb80-a965-11e9-8a47-99acf98e1968.png)

Finally, paste in the message box you use to write the ml.lib data and add the name of the file desired.

For example, if your max patch was saved on the Desktop, your write message should look something like this:

`(write /Users/Nicco/Desktop/_18_9_18_32)`

**Comment by rudxokim** [comment]
Yep. Full path works. 

Thanks for your support.

Regards, Kim
