### ISSUE TITLE
unable to load object bundle executable

### ISSUE THREAD

**Issue by jotel-california** [irllabs/ml-lib#167]
I was using ml.lib on my macbook pro on osx yosemite, I got all externals apart from ml.anbc to work. however, when i try to use the library on my imac with osx mojave I get the error "unable to load object bundle executable" in the console. tried to load earlier versions, to no avail.

**Comment by NiccoloGranieri** [comment]
Hi @jotel-california, I'm sorry to hear that you're encountering issues. Just to double check, are you using the latest version of ml.lib available on the Max Package Manager? (aka ml.lib 1.0.3?)

**Comment by jotel-california** [comment]
Hi there! In the meantime I could fix the issue myself, I now use Max 8 Standalone and now it works fine, except from the ml.anbc object (there I get the "no such object" error), although all the others worked fine. I had Max 8 installed on my Macbook, so there it worked fine, and now I updated to Max 8 on my other Machine. I also tried installing previous Versions of ml.lib, but none of them seemed to work in Max 7. versionwise, I used the latest version pf max 7 before, and now i'm on the latest version of Max 8.
ml.svm worked wonders with my bachelors thesis, so thanks :)

**Comment by NiccoloGranieri** [comment]
Hi @jotel-california, after a bit of investigation it looks like [ml.anbc] has never been included in the Max package release. It might have been in some old release of ml-lib, But it was removed at some point due to lack of reliability and overall not working as we expected it to.

However, if you used ml.anbc for a specific reason, would you mind explaining it? We are currently in the midst of a development stage for ml.lib, so if you really think ml.anbc would be a good addition you could think about making a feature request. In this way we could examine your specific case and see what can be done in terms of re-implementing it in the max package.
