### ISSUE TITLE
Can't run the library on apple silicon

### ISSUE THREAD

**Issue by LuigiCosi** [irllabs/ml-lib#188]

**Comment by LuigiCosi** [comment]
<img width="835" alt="Screenshot 2024-05-16 at 23 43 31" src="https://github.com/irllabs/ml-lib/assets/20774005/021996d3-5721-4aa5-8f69-c58b452836a1">

**Comment by NiccoloGranieri** [comment]
Hi Luigi,

thanks for the interest in ml.lib. The documentation is outdated, and I will take the opportunity to update it in the next few days, so thank you for pointing it out.

We have stopped releasing the package on Deken and have opted to use the GitHub releases page instead for Pd. Our latest release addresses specifically macOS ARM compatibility, and can be found [here](https://github.com/irllabs/ml-lib/releases/tag/1.1.5). Download [ml.lib-1.1.5-macOS.zip](https://github.com/irllabs/ml-lib/releases/download/1.1.5/ml.lib-1.1.5-macOS.zip), unzip, move the ml.lib folder in "/Users/_yourHomeFolder_/Documents/Pd" and set the correct path from the Pd preferences. You can follow [this](https://forum.pdpatchrepo.info/topic/6743/how-to-install-externals-libraries-gui-plug-ins-etc) guide if you're unsure.

Note: you might struggle to open the externals the first time due to quarantine reasons. macOS will complain and tell you it is protecting you from malicious software. To overcome this issue, select all the ".pd_darwin" files in the ml-lib folder, right-click and "Open with" any application (TextEdit will do just fine). Once macOS has done verifying the files, it will open a bunch of text files that you can ignore, and close. From that point on, you should be able to use ml.lib in Pd.

I'm sorry if this procedure is quite complex, and please do let me know if you need further clarification.

Niccolò

**Comment by LuigiCosi** [comment]
Hi @NiccoloGranieri thank you so much for your help. I completely missed your message. I owe you a coffee!

I did follow the steps you provided but I was not able to make it work unfortunately.

Dowloaded and unzip the folder
Put the folder into documents/Pd/externals
set the path in pd

I'm on M3 macbook Pro, what can I do? any help is greatly appreciated as I'm very sad I can't get to use it as I used to on my intel machine..



<img width="965" alt="Screenshot 2024-06-14 at 17 43 57" src="https://github.com/irllabs/ml-lib/assets/20774005/7302f3a7-8ead-4091-b6dc-d1702c0240d0">


<img width="975" alt="Screenshot 2024-06-14 at 17 42 06" src="https://github.com/irllabs/ml-lib/assets/20774005/2422d273-11c9-4388-8c6f-b85821a12506">

**Comment by NiccoloGranieri** [comment]
Hi @LuigiCosi, did you read the step I left for you in the "Note:" section? This looks exactly like a quarantine issue: Pd can find the files, but macOS doesn't allow the use of them. Please try to follow that step and let me know if it works.

**Comment by LuigiCosi** [comment]
Hi @NiccoloGranieri , I found why the problem might occur: I run the experimental double-precision version of the Pure Data [0.54-1-Pd64](https://puredata.info/downloads/pure-data/releases/0.54-1-pd64). 

When I try to use the lib on NOT the experimental double precision **it works**.

Should the lib be recompiled to run on the double precision version? 

thanks

Luigi

**Comment by NiccoloGranieri** [comment]
Hi @LuigiCosi, glad you managed to make it work. I don't think it's simply a matter of recompiling, but this issue is outside my area of expertise. I'll close this thread and re-open a new one that focuses on the issue at hand. However, I wouldn't hold my breath as I doubt that we will be addressing this anytime soon, or at least until the double-precision experimental version gets merged into Pd's current release.

**Comment by LuigiCosi** [comment]
@NiccoloGranieri I totally understand. Thank you for the support.
